pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Cloning repository...'
                git branch: 'main', url: 'https://github.com/Satishganiyada/Daily-TO-DO.git'
            }
        }

        stage('Build') {
            steps {
                dir('nodejsapp') {  // <-- change to your app folder
                    echo 'Installing dependencies...'
                    sh 'npm install'
                }
            }
        }

        stage('Test') {
            steps {
                dir('nodejsapp') {
                    echo 'Running tests...'
                    sh 'npm test || echo "No tests found, skipping..."'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('nodejsapp') {
                    echo 'Building Docker image...'
                    sh 'sudo docker build -t my-node-app .'
                }
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying container...'
                sh 'sudo docker rm -f my-node-app || true'
                sh 'sudo docker run -d -p 3000:3000 --name my-node-app my-node-app'
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}

